wcs_coav_terrain:
    resource: "@WCSCoavBundle/Controller/TerrainController.php"
    type:     annotation

wcs_coav_reservation:
    resource: "@WCSCoavBundle/Controller/ReservationController.php"
    type:     annotation

wcs_coav_flight:
    resource: "@WCSCoavBundle/Controller/FlightController.php"
    type:     annotation

wcs_coav_plane_model:
    resource: "@WCSCoavBundle/Controller/PlaneModelController.php"
    type:     annotation

wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing.yml"
    prefix:   /


