<?php

namespace WCS\CoavBundle\Repository;

/**
 * TerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerrainRepository extends \Doctrine\ORM\EntityRepository
{
}
